"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Arkhai',
 'project_name': 'Grant Accord Escrow',
 'track': 'Arkhai',
 'pitch': 'An escrow-ready agreement layer that turns natural-language grant or '
          'service terms into verifiable release checkpoints.',
 'idea_titles': ['Natural-Language Grant Agreements',
                 'Git-Commit Trading for Public Goods',
                 'Escrowed Octant Deliverables'],
 'architecture_summary': 'The repo models natural-language agreements and escrow '
                         'checkpoints for public-goods or service deals. A contract '
                         'stores agreement hashes and release policies while Python '
                         'scripts turn negotiation state into verifiable escrow '
                         'actions.',
 'overlap_targets': ['Octant',
                     'ENS',
                     'Filecoin',
                     'SelfProtocol',
                     'PayWithLocus',
                     'Markee'],
 'primary_contract_name': 'GrantAccordEscrow',
 'primary_python_module': 'arkhai_accord',
 'category': 'agreements',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'counterparties',
                       'description': 'Wallets, ENS names, and agreement '
                                      'counterparties.'},
                      {'name': 'release_conditions',
                       'description': 'Natural-language milestones and escrow '
                                      'checkpoints.'},
                      {'name': 'proof_bundle',
                       'description': 'Evidence hashes and settlement artifacts.'},
                      {'name': 'receipts',
                       'description': 'Submission notes and receipt anchors.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for GrantAccordEscrow.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'arkhai_accord.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Arkhai',
               'docs_url': 'https://arkhai.ai/',
               'env_vars': ['ARKHAI_API_KEY', 'ARKHAI_ESCROW_URL'],
               'endpoint_env': 'ARKHAI_ESCROW_URL',
               'action_kind': 'rest_json',
               'purpose': 'Stage natural-language agreements and escrow checkpoints.'},
              {'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'SelfProtocol',
               'docs_url': 'https://docs.self.xyz/',
               'env_vars': ['SELF_PROTOCOL_API_KEY', 'SELF_VERIFICATION_URL'],
               'endpoint_env': 'SELF_VERIFICATION_URL',
               'action_kind': 'rest_json',
               'purpose': 'Gate sensitive actions behind privacy-preserving proofs.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'Markee',
               'docs_url': 'https://markee.xyz/',
               'env_vars': ['MARKEE_API_KEY', 'MARKEE_MESSAGE_URL'],
               'endpoint_env': 'MARKEE_MESSAGE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish GitHub-adjacent build stories and repo messages.'}],
 'actions': [{'id': 'arkhai_agreement_stage',
              'target': 'arkhai',
              'purpose': 'Use Arkhai for a bounded action in this repo.',
              'partner': 'Arkhai',
              'action_kind': 'rest_json',
              'max_amount_usd': 30,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Arkhai only after a dry-run artifact exists.',
                        'Use https://arkhai.ai/ for credential setup.']},
             {'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 95,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 90,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 85,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'selfprotocol_zk_verify',
              'target': 'selfprotocol',
              'purpose': 'Use SelfProtocol for a bounded action in this repo.',
              'partner': 'SelfProtocol',
              'action_kind': 'rest_json',
              'max_amount_usd': 3,
              'priority': 80,
              'sensitivity': 'high',
              'notes': ['Call SelfProtocol only after a dry-run artifact exists.',
                        'Use https://docs.self.xyz/ for credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'markee_repo_message',
              'target': 'markee',
              'purpose': 'Use Markee for a bounded action in this repo.',
              'partner': 'Markee',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 70,
              'sensitivity': 'low',
              'notes': ['Call Markee only after a dry-run artifact exists.',
                        'Use https://markee.xyz/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
